"""Project cleanup utility.

Safe mode removes debug and temporary files.
Deep mode additionally removes generated assets under projects/*/assets and projects/*/output.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


def _collect_paths(base: Path, project: str | None, deep: bool) -> list[Path]:
    paths: list[Path] = []

    if project:
        project_roots = [base / "projects" / project]
    else:
        project_root = base / "projects"
        project_roots = [p for p in project_root.iterdir() if p.is_dir()] if project_root.exists() else []

    for root in project_roots:
        paths.extend(root.glob("debug_llm_response*.txt"))
        temp_audio = root / "output" / "temp-audio.m4a"
        if temp_audio.exists():
            paths.append(temp_audio)

        if deep:
            for folder in ("assets", "output"):
                p = root / folder
                if p.exists():
                    paths.append(p)

    # Repository-level test artifacts
    output_dir = base / "output"
    if output_dir.exists():
        paths.extend(output_dir.glob("test_*.mp4"))
        paths.extend(output_dir.glob("test_*.srt"))
        temp_audio = output_dir / "temp-audio.m4a"
        if temp_audio.exists():
            paths.append(temp_audio)

    # Python cache directories
    paths.extend(base.glob("**/__pycache__"))
    return paths


def _remove_path(path: Path) -> None:
    if path.is_dir():
        shutil.rmtree(path, ignore_errors=True)
    elif path.exists():
        path.unlink(missing_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Clean temporary files generated by AutoVideo.")
    parser.add_argument("--project", help="Project folder name under projects/ (e.g. number3)")
    parser.add_argument("--deep", action="store_true", help="Also remove generated project assets/output folders")
    parser.add_argument("--dry-run", action="store_true", help="Only print paths, do not delete")
    args = parser.parse_args()

    base = Path(__file__).resolve().parent
    targets = sorted(set(_collect_paths(base, args.project, args.deep)))

    if not targets:
        print("No temporary files found.")
        return

    print(f"Found {len(targets)} path(s):")
    for t in targets:
        print(f"  - {t.relative_to(base)}")

    if args.dry_run:
        print("Dry run complete.")
        return

    for t in targets:
        _remove_path(t)
    print("Cleanup complete.")


if __name__ == "__main__":
    main()
